function [xcor,ycor,zcor,W] = posWalk(pos,ocean,W)
x = pos(1);
y = pos(2);
z = pos(3);

neighPos =  [x,y,z+1;...
             x,y,z-1;...
             x,y+1,z;...
             x,y-1,z;...
             x+1,y,z;...
             x-1,y,z];

neighVals = [ocean(x,y,z+1),...
             ocean(x,y,z-1),...
             ocean(x,y+1,z),...
             ocean(x,y-1,z),...
             ocean(x+1,y,z),...
             ocean(x-1,y,z)];

length(find(neighVals == 0));

goodInd = neighPos(randsample(find(neighVals == 0),1),:);
W = W*length(find(neighVals == 0))/3;

xcor = goodInd(1);
ycor = goodInd(2);
zcor = goodInd(3);
end

